name: Mpack
version: 1.0.0
api-version: 1.18
authors: ["Robins Software"]
main: ca.robinssoftware.mpack.Main
description: A user-friendly package manager for Spigot.
load: STARTUP
commands:
   mpack:
      aliases: [packages, pkg, pack]